x-default-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "300m"
    max-file: '3'

networks:
  monitoring_network:
    driver: bridge

volumes:
  prometheus-data: null

services:
  telegraf:
    build:
      context: .
    environment:
      - HOSTNAME=telegraf-host
    hostname: telegraf-host
    volumes:
      - ./endpoints.json:/scripts/endpoints.json:ro
    ports:
      - "9126:9126"
    networks:
      - monitoring_network
    logging: *default-logging

  prometheus:
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=7d'
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - monitoring_network
    logging: *default-logging

  nginx:
    image: nginx:latest
    volumes:
      - ./static/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    networks:
      - monitoring_network
    logging: *default-logging