{
 "title": "API Monitoring Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Uptime",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(http_response_http_response_code{job='telegraf', status_code='200'}[$__range])) by (source) / sum(count_over_time(http_response_http_response_code{job='telegraf'}[$__range])) by (source)",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Service availability",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "http_response_http_response_code{job='telegraf'}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Get block latency",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_response_response_time{job='telegraf'}",
     "legendFormat": "{{source}}"
    }
   ]
  }
 ]
}